// <auto-generated />
namespace TestingSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modified13team1v10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modified13team1v10));
        
        string IMigrationMetadata.Id
        {
            get { return "201903010226097_Modified13team1v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
